# Generated by Django 4.0.2 on 2022-02-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('full_address', models.CharField(max_length=450)),
                ('update_date', models.DateField(max_length=10)),
                ('created_date', models.DateField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('stamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('verbose_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Типы',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('user', models.CharField(max_length=15, verbose_name='Пользователь')),
                ('facility', models.ManyToManyField(related_name='list', to='myapp.Facility')),
            ],
            options={
                'verbose_name': 'Списки',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='myapp.facilitytype'),
        ),
    ]
