# Generated by Django 4.0.2 on 2022-02-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='num',
            new_name='cad_num',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='type',
            new_name='obj_type',
        ),
    ]
