// Objects Types:
// parcel, building, facility, flat


// Rosreestr API
GET https://rosreestr.ru/fir_lite_rest/api/gkn/fir_lite_object/{{flat}}
Accept: application/json
User-Agent: restclient



###
// Get cad data
GET {{host}}/object?cad_num={{parcel}}
Accept: application/json

###
// Get cad data
GET {{host}}/object?cad_num={{building}}
Accept: application/json

###
// Get cad data
GET {{host}}/object?cad_num={{flat}}
Accept: application/json

###
// Get cad data
GET {{host}}/object?cad_num={{construction}}
Accept: application/json